port=$1
server="localhost"
origin="Origin: http://localhost:12223/"
echo "RESURS: KORISNICI"
echo "GET"
curl -H "$origin" -X GET "http://localhost:12223/servis/korisnici/"
echo ""
echo "POST"
curl -H "$origin" -X POST "http://localhost:12223/servis/korisnici/" -H 'Content-Type: application/json' -d '{"ime":"Test", "prezime":"Test", "lozinka":"123456", "email":"test3@foi.unizg.hr", "korime":"test", "tip_korisnika_id":"1"}'
echo ""
echo "DELETE"
curl -H "$origin" -X DELETE "http://localhost:12223/servis/korisnici/"
echo ""
echo "PUT"
curl -H "$origin" -X PUT "http://localhost:12223/servis/korisnici/"
echo ""
echo ""
echo "RESURS: KORISNICI/lpolak22"
echo "GET"
curl -H "$origin" -X GET "http://localhost:12223/servis/korisnici/lpolak22"
echo "POST"
curl -H "$origin" -X POST "http://localhost:12223/servis/korisnici/lpolak22" -H 'Content-Type: application/json' -d '{"ime":"Test", "prezime":"Test", "lozinka":"123456", "email":"test3@foi.unizg.hr", "korime":"test", "tip_korisnika_id":"1"}'
echo "PUT"
curl -H "$origin" -X PUT "http://localhost:12223/servis/korisnici/lpolak22"
echo ""
echo "DELETE"
curl -H "$origin" -X DELETE "http://localhost:12223/servis/korisnici/lpolak22"
echo ""
echo ""
echo "GET prijava tocna"
curl -H "$origin" -X POST "http://localhost:12223/servis/korisnici/lpolak22/prijava" -H 'Content-Type: application/json' -d '{"lozinka":"123456"}'
echo ""
echo "GET prijava kriva"
curl -H "$origin" -X POST "http://localhost:12223/servis/korisnici/lpolak22/prijava" -H 'Content-Type: application/json' -d '{"lozinka":"12345"}'
echo ""
echo ""
echo "RESURS: OSOBA/test"
echo "PUT"
echo "Staro"
curl -H "$origin" -X GET "http://localhost:12223/servis/osoba/21"
echo ""
echo "Azuriram"
curl -H "$origin" -X POST "http://localhost:12223/servis/osoba" -H 'Content-Type: application/json' -d '{"id":4, "ime_prezime":"Test", "poznat_po":"tekst", "slika":"putanja", "popularnost":3.4}'
echo ""
echo "PUT"
curl -H "$origin" -X PUT "http://localhost:12223/servis/osoba"
echo ""
echo "DELETE"
curl -H "$origin" -X DELETE "http://localhost:12223/servis/osoba/21"
echo ""
echo ""
echo "Novo"
echo "GET"
curl -H "$origin" -X GET "http://localhost:12223/servis/osoba?stranica=1"
echo ""
echo "DELETE"
curl -H "$origin" -X DELETE "http://localhost:12223/servis/osoba?stranica=1"
echo ""
echo "PUT"
curl -H "$origin" -X PUT "http://localhost:12223/servis/osoba?stranica=1"
echo ""
echo "POST"
curl -H "$origin" -X POST "http://localhost:12223/servis/osoba" -H 'Content-Type: application/json' -d '{"id":23, "ime_prezime":"Test", "poznat_po":"tekst", "slika":"putanja", "popularnost":3.4}'
echo ""
echo ""
echo "GET"
curl -H "$origin" -X GET "http://localhost:12223/servis/film/21"
echo ""
echo "Azuriram"
curl -H "$origin" -X POST "http://localhost:12223/servis/film" -H 'Content-Type: application/json' -d '{"id":4, "ime_prezime":"Test", "poznat_po":"tekst", "slika":"putanja", "popularnost":3.4}'
echo ""
echo "PUT"
curl -H "$origin" -X PUT "http://localhost:12223/servis/film/21"
echo ""
echo "DELETE"
curl -H "$origin" -X DELETE "http://localhost:12223/servis/film/1"
echo ""
echo ""
echo ""
echo ""
echo "GET"
curl -H "$origin" -X GET "http://localhost:12223/servis/osoba/19/film?stranica=1"
echo ""
echo "POST"
curl -H "$origin" -X POST "http://localhost:12223/servis/osoba/19/film?stranica=1" -H 'Content-Type: application/json' -d '{"id":4, "ime_prezime":"Test", "poznat_po":"tekst", "slika":"putanja", "popularnost":3.4}'
echo ""
echo "PUT"
curl -H "$origin" -X PUT "http://localhost:12223/servis/osoba/19/film?stranica=1"
curl -H "$origin" -X PUT "http://localhost:12223/servis/osoba/3/film" -H "Content-Type: application/json" -d '{"filmovi": [4, 5, 6]}'
echo ""
echo "DELETE"
curl -H "$origin" -X DELETE "http://localhost:12223/servis/film/1"

servis/osoba/{id}/film?stranica=broj
